package net.xngo.utils.java.util;

import java.util.ArrayList;
/**
 * http://stackoverflow.com/questions/1963806/is-there-a-fixed-sized-queue-which-removes-excessive-elements
 * @author Xuan Ngo
 *
 * @param <E>
 */
public class CircularArrayList<E> extends ArrayList<E> 
{
  
  /**
   * serialVersionUID is auto generated by Eclipse.
   */
  private static final long serialVersionUID = 2784995695378956707L;
  
  private int maxSize;
  private int position = 0;

  public CircularArrayList(int size)
  {
    this.maxSize = size;
  }

  @Override
  public boolean add(E e)
  {
    if(!(this.position<this.maxSize))
      this.position = 0;
      
    super.add(this.position, e);
    this.position++;
    
    // Return something so that it has the same 
    //  signature as java.util.ArrayList<E>.add(E e).
    return false; 
  }
  
  public int getMaxSize()
  {
    return this.maxSize;
  }
}